pull request about issue #2062 (car_racing.py memory leaking issue )
openai/gym pull request #2096
Opened 2020-11-17 04:11 UTC by Jaekyung-Cho

Pull request about issue #2062 

There is memory leaking issue caused by pyglet module and solved with simply delete after drawing vertexs

2021-01-12 16:22 UTC, SwapnilPande requested changes
Hi @Jaekyung-Cho,

I've been debugging the same issue. Looks like we need to add `vl.delete()` after `vl.draw` in function `render_indicators` (line 592). It looks like the memory consumption is still growing after this change, but much much slower.

2021-01-12 16:28 UTC, Jaekyung-Cho commented
> Hi @Jaekyung-Cho,
> 
> I've been debugging the same issue. Looks like we need to add `vl.delete()` after `vl.draw` in function `render_indicators` (line 592). It looks like the memory consumption is still growing after this change, but much much slower.

Exactly. Memory leaking still remain, but I cannot find where it occur. Though slower leaking issues doesn't matter in my case.

2021-01-12 17:34 UTC, SwapnilPande commented
Looks like this is an issue with Box2D, I was able to isolate the memory leak down to creating the tiles in `_create_track`. Despite calling `DestroyBody` on all of the tiles in `_destroy`, Box2D does not properly destroy the tiles sometimes. This memory leak can be reproduced with this minimum code:

```
import Box2D
from Box2D.b2 import fixtureDef, polygonShape

import psutil
import os

def memory_used():
    return psutil.Process(os.getpid()).memory_info().rss * 1e-6  # To megabyte


world = Box2D.b2World((0,0))


road1_l = (0, 0)
road1_r = (0, 1)
road2_l = (1, 0)
road2_r = (1, 1)
vertices = [road1_l, road1_r, road2_r, road2_l]

fd_tile = fixtureDef(
                shape = polygonShape(vertices=
                    [(0, 0),(1, 0),(1, -1),(0, -1)]))

fd_tile.shape.vertices = vertices

for i in range(1000000):
    t = world.CreateStaticBody(fixtures=fd_tile)
    world.DestroyBody(t)

    if i % 10 == 0:
        print('Ram Used: %f' % memory_used())
```

Looks like it's time to submit an issue to pybox2d. :D

The slow leaking doesn't matter in my case either, though it'd be nice to have this issue resolved. Would you be able to add the second `vl.delete()` statement to make the PR complete for the gym codebase?

2021-01-13 01:38 UTC, Jaekyung-Cho commented
> Looks like this is an issue with Box2D, I was able to isolate the memory leak down to creating the tiles in `_create_track`. Despite calling `DestroyBody` on all of the tiles in `_destroy`, Box2D does not properly destroy the tiles sometimes. This memory leak can be reproduced with this minimum code:
> 
> ```
> import Box2D
> from Box2D.b2 import fixtureDef, polygonShape
> 
> import psutil
> import os
> 
> def memory_used():
>     return psutil.Process(os.getpid()).memory_info().rss * 1e-6  # To megabyte
> 
> 
> world = Box2D.b2World((0,0))
> 
> 
> road1_l = (0, 0)
> road1_r = (0, 1)
> road2_l = (1, 0)
> road2_r = (1, 1)
> vertices = [road1_l, road1_r, road2_r, road2_l]
> 
> fd_tile = fixtureDef(
>                 shape = polygonShape(vertices=
>                     [(0, 0),(1, 0),(1, -1),(0, -1)]))
> 
> fd_tile.shape.vertices = vertices
> 
> for i in range(1000000):
>     t = world.CreateStaticBody(fixtures=fd_tile)
>     world.DestroyBody(t)
> 
>     if i % 10 == 0:
>         print('Ram Used: %f' % memory_used())
> ```
> 
> Looks like it's time to submit an issue to pybox2d. :D
> 
> The slow leaking doesn't matter in my case either, though it'd be nice to have this issue resolved. Would you be able to add the second `vl.delete()` statement to make the PR complete for the gym codebase?

Oh! I think I misunderstand your mention. I'm so sorry about that. I add vl.delete() in render_indicators function and make PR now. Thank you for your help.

2021-01-17 18:25 UTC, hirekk commented
`vl.delete()` should also be added at the end of the `render_road` method (line 530), since the memory leak still occurs. As far as I can tell, this fixes the issue completely.

2021-01-20 19:10 UTC, yoavalon commented
This solution works well for me. Memory remains low,

2021-01-23 01:03 UTC, SlipknotTN commented
Me too

2021-02-10 19:45 UTC, xeviknal commented
Any updates in this one? Do you think this PR is any close to be merged?

2021-02-12 17:10 UTC, xeviknal approved these changes
I've been able to reproduce the issue. Once the PR is applied, the memory leak is gone or at least not exploding.

2021-02-14 08:08 UTC, Jaekyung-Cho commented
> I've been able to reproduce the issue. Once the PR is applied, the memory leak is gone or at least not exploding.

Thanks for reproducing instead of me!!

2021-02-14 09:12 UTC, xeviknal commented
@pzhokhov @zuoxingdong I see you've been contributing quite a lot last months. Do you know what we can do to move this forward? are you maintainers? I am guessing this issue is making people to start forking. I'd be pretty good for this community to approach this nasty bug. thank you

2021-02-16 19:31 UTC, pzhokhov approved these changes

2021-02-16 19:31 UTC, merged