add pygame GUI render for taxi env
openai/gym pull request #2713
Opened 2022-03-23 13:52 UTC by younik

I added pygame GUI render for Taxi env with `mode="human"`

Result:
![Screenshot from 2022-03-23 10-22-49](https://user-images.githubusercontent.com/42100908/159709573-608b7730-98ba-404c-9814-96fe7eace157.png)

2022-03-24 05:17 UTC, andrewtanJS reviewed
Overall looks good, and I only have a few minor comments

2022-03-24 05:17 UTC, andrewtanJS commented on gym/envs/toy_text/taxi.py
> +import pygame
I think we could defer the pygame import to the `_render_gui()` method, so that #2691 is preemptively solved (similar to #2712)

2022-03-24 05:17 UTC, andrewtanJS commented on gym/envs/toy_text/taxi.py
> +        self.window.blit(background, background.get_rect())
Do we need to initialize another surface for the background, or can we just do `self.window.fill((20, 24, 35))` to begin with?

2022-03-24 12:39 UTC, Markus28 requested changes
- It seems that the framerate is not locked (see other PyGame envs how to do that)
- We should probably have a `close` method as in the other PyGame environments

Some remarks that are not really that are not that important/maybe not worth fixing:
- The destination can occasionally block out the taxi
- The way the destination is displayed suggests that it also presents an obstacle if it is at one of the bottom locations. But actually, the taxi can "move right through it". Idk if it is actually possible or worth fixing, but I think one might avoid misunderstandings if one could manage to make the destination always line up with a median.
- Might make sense to reset `self.taxi_orientation` in `reset` but that doesn't really matter I guess

2022-03-24 16:44 UTC, younik commented
Hello @Markus28, thanks for your review!

I integrated points 1, 2 and 5.

> The destination can occasionally block out the taxi

This problem is only graphically, as pointed out in point 4th, the taxi can pass through it.

> The way the destination is displayed suggests that it also presents an obstacle if it is at one of the bottom locations. But actually, the taxi can "move right through it". Idk if it is actually possible or worth fixing, but I think one might avoid misunderstandings if one could manage to make the destination always line up with a median.

I would like to make it nicer, but I have no idea how to do it (without having complicated code/particular cases) with the current hotel image.

2022-03-27 03:01 UTC, trigaten commented
From what I understand, this looks good. I second the confusion with the Taxi being hidden behind the building/it being an obstacle. Maybe reduce the building alpha?

2022-03-27 19:09 UTC, younik commented
@trigaten 

Reducing the building alpha, the result is like this:
![Screenshot from 2022-03-27 21-03-23](https://user-images.githubusercontent.com/42100908/160296657-246fc53a-cca5-4dce-86f8-ee170b5c8629.png)

We need something to specify which one is the destination, this is the aim of the building. Moreover, the taxi can stay in the destination tile.

2022-03-27 19:19 UTC, trigaten commented
@younik I like the reduced alpha. It also sort of shows that the taxi can pass through. Maybe try reducing a bit more?

2022-03-29 20:13 UTC, younik commented
> @younik I like the reduced alpha. It also sort of shows that the taxi can pass through. Maybe try reducing a bit more?

I pushed the version with alpha
![taxi](https://user-images.githubusercontent.com/42100908/160698540-0dd78f14-7068-4fb6-9cef-e7d73faa988d.png)

2022-03-30 18:07 UTC, younik commented
Is the pre-commit failure my fault? I run it locally and it is ok

2022-03-30 18:18 UTC, Markus28 commented
Probably this: 
https://github.com/psf/black/issues/2964#issue-1183788875

2022-04-02 12:07 UTC, pseudo-rnd-thoughts commented
This PR fixed this issue now I believe, https://github.com/openai/gym/pull/2724, so we just need to rerun the pre-commit

2022-04-02 14:20 UTC, merged