added phys2d lunar_lander
openai/gym pull request #2880
Opened 2022-06-10 20:23 UTC by 1b15

# Description

- added a brax implementation of lunar_lander, allowing it to be run on GPU / TPU
- a new heightmap is generated on reset, which takes up some time because a new brax system needs to be generated as well

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### Gifs
(the gif preview is slow because it doesn't support 100 fps gifs, view it locally for original speed)

demo with strong initial push:
![lunar_lander_example](https://user-images.githubusercontent.com/39133020/173138569-8fc189b3-811f-47c7-b28d-bfc8d114a535.gif)

demo with winds:
![lunar_lander_with_wind_example](https://user-images.githubusercontent.com/39133020/173138583-78330180-4bb3-4695-8130-759fcf91c08b.gif)

demo with continuous control:
![lunar_lander_continuous_example](https://user-images.githubusercontent.com/39133020/173144229-a2ad6aac-337b-475b-b9a8-7f5ae183debc.gif)

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Comments to the checklist:
- a warning is thrown for "unsupported collider pair: box, box"

2022-06-12 11:02 UTC, 1b15 commented
New tests are failing because they require the latest brax version, which isn't on PyPi yet.

2022-07-26 16:48 UTC, 1b15 commented
Notes on bipedal walker:
- main parts, i.e. basic physics, observations (including vectorized raycasting for lidar) and rendering are implemented
- I didn't train any agent and couldn't get the given heuristic to work yet, so some parameter tweaks might be necessary
    - most relevant parameters are editable through the constants at the top of the file
    - some (e.g. hull inertia) are in the config string
    - despite my best efforts, I wouldn't exclude the possibility that actions and observations don't fully match their counterparts in box2d (e.g. order of actuators, sign flips, etc.)
- we still use default numpy for einsum and linspace since it's not in the jax utils
- we'll probably have to make the code a bit nicer once we have a template for brax envs
- hardcore mode isn't implemented yet

![out](https://user-images.githubusercontent.com/39133020/181060968-d27b0f40-5ae0-4c51-be41-f34f3c6f5cc5.gif)

2022-08-08 20:36 UTC, pseudo-rnd-thoughts requested changes
Thanks for the work, from the gifs, it looks great. I have added a couple of comments to help. Our plan is that soon, we will have a jax environment checker to ensure correctness that we can add as a test.

2022-08-08 20:36 UTC, pseudo-rnd-thoughts commented on gym/envs/phys2d/bipedal_walker.py
> +if __name__ == "__main__":
This is a legacy feature of bipedal walker, we can remove

2022-08-08 20:36 UTC, pseudo-rnd-thoughts commented on gym/envs/phys2d/bipedal_walker.py
> +    def render(self, mode="human"):
Personally, as the phys2d are about performance and vectorisation then I don't think we should include the rendering code for now. Possibly when the jax graphics module is release, we could replace with that

2022-08-08 20:36 UTC, pseudo-rnd-thoughts commented on gym/envs/phys2d/bipedal_walker.py
> +        _SYSTEM_CONFIG = """
This should be moved to `init` as we don't understand users change the parameters between resets

2022-08-08 20:36 UTC, pseudo-rnd-thoughts commented on gym/envs/phys2d/bipedal_walker.py
> +from brax import jumpy as jp
Our plan is that jumpy is solely used by the wrappers for easy compatibility between numpy and jax. 
But with the environment, to ensure performance, we should only use jax.numpy for operations.

We will provide jax based spaces

2022-08-08 20:36 UTC, pseudo-rnd-thoughts commented on gym/envs/phys2d/bipedal_walker.py
> +    def _to_2d(self, arr):
Could you add some docstrings to explain the purpose of the function, repeat this comment for the other functions

2022-08-08 20:36 UTC, pseudo-rnd-thoughts commented on gym/envs/phys2d/bipedal_walker.py
> +        state = [
Should this not be a jax / numpy array?

2022-08-08 20:36 UTC, pseudo-rnd-thoughts commented on setup.py
> +    "phys2d": ["brax>=0.0.13", "pyyaml>=6.0"],
Why is `pyyaml` required

2022-08-08 20:36 UTC, pseudo-rnd-thoughts commented on tests/envs/test_phys2d_lunar_lander.py
> +import pytest
I believe we can remove all of these tests

2022-08-08 20:36 UTC, pseudo-rnd-thoughts commented on py.Dockerfile
> +RUN if [ "python:${PYTHON_VERSION}" = "python:3.6.15" ] ; then pip install .[box2d,phys2d,classic_control,toy_text,other] pytest=="7.0.1" --no-cache-dir; else pip install .[testing] --no-cache-dir; f
As jax is 3.7+ then phys2d should not be added here. This is only for python 3.6 testing.

2022-08-08 20:36 UTC, pseudo-rnd-thoughts commented on gym/envs/phys2d/lunar_lander.py
> +import warnings
Basically all of the same comments for lunar lander, remove heuristics and `__main__`, move protobuf and change to jax.numpy

2022-11-11 20:26 UTC, closed without merging